<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/functions.php';
$admin=require_admin('reports');$electionId=(int)($_GET['id']??active_election_id());$election=election_by_id($electionId);if(!$election){flash('error','Выборы не найдены.');redirect('elections.php');}
$metrics=election_metrics($electionId);$rows=result_rows($electionId);$classes=turnout_by_class($electionId);$total=max(1,$metrics['votes']);$st=db()->prepare("SELECT strftime('%d.%m %H:00',created_at) AS period,COUNT(*) AS count FROM votes WHERE election_id=? GROUP BY strftime('%Y-%m-%d %H',created_at) ORDER BY MIN(created_at)");$st->execute([$electionId]);$timeline=$st->fetchAll();$elections=db()->query('SELECT id,title,status FROM elections ORDER BY id DESC')->fetchAll();
$pageTitle='Отчёты';$isAdminArea=true;require dirname(__DIR__).'/partials/header.php';
?>
<section class="section"><div class="container"><div class="dashboard-heading"><div><span class="kicker">Аналитика</span><h1>Отчёты и экспорт</h1><p class="lead"><?=e($election['title'])?></p></div><form method="get"><select name="id" onchange="this.form.submit()"><?php foreach($elections as $item):?><option value="<?=(int)$item['id']?>" <?=(int)$item['id']===$electionId?'selected':''?>><?=e($item['title'])?></option><?php endforeach;?></select></form></div>
<div class="metric-grid"><article class="metric-card"><span>Голоса</span><strong><?=$metrics['votes']?></strong><small>совпадают с участием: <?=$metrics['participants']?></small></article><article class="metric-card"><span>Явка</span><strong><?=$metrics['turnout']?>%</strong><small><?=$metrics['participants']?> из <?=$metrics['eligible']?></small></article><article class="metric-card"><span>Не участвовали</span><strong><?=$metrics['remaining']?></strong><small>активных учеников</small></article><article class="metric-card"><span>Статус</span><strong class="metric-text"><?=e(election_status_label($election['status']))?></strong><small><?=e(format_datetime($election['end_at']))?></small></article></div>
<div class="export-toolbar"><a class="button primary" href="export.php?type=results_xlsx&id=<?=$electionId?>">Результаты Excel</a><a class="button secondary" href="export.php?type=results_csv&id=<?=$electionId?>">Результаты CSV</a><a class="button secondary" href="export.php?type=turnout_xlsx&id=<?=$electionId?>">Явка Excel</a><a class="button secondary" href="export.php?type=participation_csv&id=<?=$electionId?>">Список участия CSV</a><a class="button secondary" target="_blank" href="export.php?type=protocol&id=<?=$electionId?>">Протокол / сохранить PDF</a><a class="button secondary" target="_blank" href="../projector.php?id=<?=$electionId?>">Проектор</a></div>
<div class="results-layout"><section class="panel"><div class="panel-heading"><div><span class="kicker">Итоги</span><h2>Кандидаты</h2></div></div><div class="compact-results"><?php foreach($rows as $row):$p=round((int)$row['vote_count']/$total*100,1);?><div class="compact-result"><div class="result-line"><strong><?=e($row['full_name'])?></strong><span><?=(int)$row['vote_count']?> · <?=$p?>%</span></div><div class="progress"><span style="width:<?=$p?>%;background:<?=e($row['color'])?>"></span></div></div><?php endforeach;?></div></section><section class="panel"><div class="panel-heading"><div><span class="kicker">Классы</span><h2>Явка</h2></div></div><div class="class-turnout-list"><?php foreach($classes as $class):?><div class="class-turnout"><div class="result-line"><strong><?=e($class['class_name'])?></strong><span><?=(int)$class['participated']?>/<?=(int)$class['eligible']?> · <?=e($class['turnout'])?>%</span></div><div class="progress"><span style="width:<?=e($class['turnout'])?>%"></span></div></div><?php endforeach;?></div></section></div>
<section class="panel"><div class="panel-heading"><div><span class="kicker">Динамика</span><h2>Голоса по часам</h2></div></div><div class="timeline-chart"><?php $max=max(1,...array_map(static fn($r)=>(int)$r['count'],$timeline?:[['count'=>1]]));foreach($timeline as $point):?><div class="timeline-column"><span style="height:<?=round((int)$point['count']/$max*180)?>px"></span><strong><?=(int)$point['count']?></strong><small><?=e($point['period'])?></small></div><?php endforeach;?><?php if(!$timeline):?><div class="empty-state">Голосов пока нет.</div><?php endif;?></div></section>
</div></section>
<?php require dirname(__DIR__).'/partials/footer.php';?>
