<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/functions.php';
$admin=require_admin();if($admin['role']!=='superadmin'){http_response_code(403);exit('Только главный администратор.');}
if(isset($_GET['download'])){$name=basename((string)$_GET['download']);$path=BACKUP_ROOT.'/'.$name;if(!is_file($path)||!str_ends_with($name,'.sqlite')){http_response_code(404);exit('Файл не найден.');}audit_log('backup_downloaded','backup',null,['file'=>$name]);header('Content-Type: application/vnd.sqlite3');header('Content-Disposition: attachment; filename="'.$name.'"');header('Content-Length: '.filesize($path));readfile($path);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$file=$_FILES['database_file']??[];if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Выберите файл SQLite.');$tmp=(string)$file['tmp_name'];if((int)$file['size']>100*1024*1024)throw new RuntimeException('Файл слишком большой.');$handle=fopen($tmp,'rb');$header=$handle?fread($handle,16):'';if($handle)fclose($handle);if($header!=="SQLite format 3\0")throw new RuntimeException('Файл не является корректной SQLite-базой.');$check=new PDO('sqlite:'.$tmp);$required=['admins','students','elections','candidates','votes','participation'];foreach($required as $table){$st=$check->prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?");$st->execute([$table]);if(!$st->fetchColumn())throw new RuntimeException('В копии отсутствует таблица '.$table.'.');}$backup=backup_database('before-restore');audit_log('backup_restore_started','backup',null,['pre_restore'=>basename($backup)]);@unlink(DB_PATH.'-wal');@unlink(DB_PATH.'-shm');if(!copy($tmp,DB_PATH))throw new RuntimeException('Не удалось заменить базу.');@chmod(DB_PATH,0664);unset($_SESSION['admin_id'],$_SESSION['admin_last_activity']);session_regenerate_id(true);redirect('login.php?restored=1');}catch(Throwable $e){flash('error',$e->getMessage());redirect('backup.php');}}
$pageTitle='Восстановление';$isAdminArea=true;require dirname(__DIR__).'/partials/header.php';
?>
<section class="section auth-section"><div class="container narrow"><div class="auth-card"><span class="eyebrow">Резервное копирование</span><h1>Восстановить базу</h1><p class="lead">Перед заменой система автоматически сохранит текущую базу. После восстановления потребуется повторный вход.</p><div class="flash flash-warning">Не восстанавливайте базу во время открытого голосования. Используйте только доверенный файл, созданный этой системой.</div><form method="post" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><label>Файл .sqlite<input type="file" name="database_file" accept=".sqlite,.db" required></label><button class="button danger-button" data-confirm="Заменить текущую базу резервной копией?">Проверить и восстановить</button></form><a class="admin-entry" href="settings.php">Вернуться в настройки</a></div></div></section>
<?php require dirname(__DIR__).'/partials/footer.php';?>
