<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/functions.php';
$admin=require_admin('candidates');
$electionId=(int)($_GET['election_id']??$_POST['election_id']??active_election_id());
$election=election_by_id($electionId);
if(!$election){flash('error','Выборы не найдены.');redirect('elections.php');}
$editable=election_is_editable($election)||$admin['role']==='superadmin';

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if(!$editable&&in_array($action,['save','toggle','delete','delete_all'],true))throw new RuntimeException('Кандидаты заблокированы после открытия голосования.');
        if($action==='save'){
            $id=(int)($_POST['id']??0);$name=trim((string)($_POST['full_name']??''));$class=trim((string)($_POST['class_name']??''));if($name===''||$class==='')throw new RuntimeException('Укажите ФИО и класс.');
            $color=(string)($_POST['color']??'#665df5');if(!preg_match('/^#[0-9a-fA-F]{6}$/',$color))$color='#665df5';
            $old=null;if($id){$old=candidate_by_id($id,$electionId);if(!$old)throw new RuntimeException('Кандидат не найден.');}
            $photo=safe_candidate_photo_upload($_FILES['photo']??[],$old['photo_path']??null);
            $values=[$name,$class,trim((string)($_POST['slogan']??'')),trim((string)($_POST['program_text']??'')),trim((string)($_POST['bio']??'')),trim((string)($_POST['achievements']??'')),trim((string)($_POST['resources_text']??'')),trim((string)($_POST['video_url']??'')),trim((string)($_POST['website_url']??'')),$photo,$color,max(0,(int)($_POST['ballot_number']??0))];
            if($id){$st=db()->prepare('UPDATE candidates SET full_name=?,class_name=?,slogan=?,program_text=?,bio=?,achievements=?,resources_text=?,video_url=?,website_url=?,photo_path=?,color=?,ballot_number=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND election_id=?');$st->execute([...$values,$id,$electionId]);audit_log('candidate_updated','candidate',$id,['election'=>$electionId]);flash('success','Кандидат обновлён.');}
            else{$st=db()->prepare('INSERT INTO candidates(election_id,full_name,class_name,slogan,program_text,bio,achievements,resources_text,video_url,website_url,photo_path,color,ballot_number) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute([$electionId,...$values]);$id=(int)db()->lastInsertId();audit_log('candidate_created','candidate',$id,['election'=>$electionId]);flash('success','Кандидат добавлен.');}
        }elseif($action==='toggle'){$id=(int)$_POST['id'];db()->prepare('UPDATE candidates SET is_active=CASE is_active WHEN 1 THEN 0 ELSE 1 END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND election_id=?')->execute([$id,$electionId]);audit_log('candidate_toggled','candidate',$id);flash('success','Статус кандидата изменён.');}
        elseif($action==='delete'){$id=(int)$_POST['id'];$st=db()->prepare('SELECT COUNT(*) FROM votes WHERE candidate_id=?');$st->execute([$id]);if((int)$st->fetchColumn()>0)throw new RuntimeException('Нельзя удалить кандидата с голосами.');$candidate=candidate_by_id($id,$electionId);db()->prepare('DELETE FROM candidates WHERE id=? AND election_id=?')->execute([$id,$electionId]);if($candidate&&!empty($candidate['photo_path'])){$photoFile=dirname(__DIR__).'/'.ltrim((string)$candidate['photo_path'],'/');if(is_file($photoFile))@unlink($photoFile);}audit_log('candidate_deleted','candidate',$id);flash('success','Кандидат удалён.');}
        elseif($action==='delete_all'){
            if(($admin['role']??'')!=='superadmin')throw new RuntimeException('Массовое удаление доступно только главному администратору.');
            $pdo=db();$st=$pdo->prepare('SELECT COUNT(*) FROM votes WHERE election_id=?');$st->execute([$electionId]);$voteCount=(int)$st->fetchColumn();if($voteCount>0)throw new RuntimeException('Нельзя удалить всех кандидатов: в этих выборах уже есть голоса. Сначала создайте отдельную новую кампанию или выполните полный сброс выборов.');
            $st=$pdo->prepare('SELECT id,photo_path FROM candidates WHERE election_id=?');$st->execute([$electionId]);$toDelete=$st->fetchAll();if(!$toDelete)throw new RuntimeException('В выбранных выборах нет кандидатов.');
            $backupPath=backup_database('before-delete-candidates-'.$electionId);$pdo->beginTransaction();$pdo->prepare('DELETE FROM candidates WHERE election_id=?')->execute([$electionId]);$pdo->commit();
            foreach($toDelete as $item){if(!empty($item['photo_path'])){$photoFile=dirname(__DIR__).'/'.ltrim((string)$item['photo_path'],'/');if(is_file($photoFile))@unlink($photoFile);}}
            audit_log('candidates_bulk_deleted','election',$electionId,['deleted'=>count($toDelete),'backup'=>basename($backupPath)]);flash('success','Все кандидаты удалены: '.count($toDelete).'. Перед удалением создана резервная копия.');
        }
    }catch(Throwable $e){flash('error',database_error_message($e));}
    redirect('candidates.php?election_id='.$electionId);
}
$editId=(int)($_GET['edit']??0);$edit=$editId?candidate_by_id($editId,$electionId):null;$st=db()->prepare('SELECT candidates.*,COUNT(votes.id) AS vote_count FROM candidates LEFT JOIN votes ON votes.candidate_id=candidates.id WHERE candidates.election_id=? GROUP BY candidates.id ORDER BY CASE WHEN ballot_number>0 THEN ballot_number ELSE 999999 END,id');$st->execute([$electionId]);$candidates=$st->fetchAll();$elections=db()->query('SELECT id,title,status FROM elections ORDER BY id DESC')->fetchAll();
$pageTitle='Кандидаты';$isAdminArea=true;require dirname(__DIR__).'/partials/header.php';
?>
<section class="section"><div class="container">
<div class="dashboard-heading"><div><span class="kicker">Бюллетень</span><h1>Кандидаты</h1><p class="lead"><?=e($election['title'])?> · <?=e(election_status_label($election['status']))?></p></div><form method="get"><select name="election_id" onchange="this.form.submit()"><?php foreach($elections as $item):?><option value="<?=(int)$item['id']?>" <?=(int)$item['id']===$electionId?'selected':''?>><?=e($item['title'])?> — <?=e(election_status_label($item['status']))?></option><?php endforeach;?></select></form></div>
<?php if(!$editable):?><div class="flash flash-warning">Кандидаты заблокированы, потому что голосование уже открывалось. Главный администратор может внести экстренное изменение, которое попадёт в журнал.</div><?php endif;?>
<section class="panel"><div class="panel-heading"><div><span class="kicker"><?=$edit?'Редактирование':'Новая запись'?></span><h2><?=$edit?e($edit['full_name']):'Добавить кандидата'?></h2></div><?php if($edit):?><a href="candidates.php?election_id=<?=$electionId?>">Отмена</a><?php endif;?></div>
<form method="post" enctype="multipart/form-data" class="form-grid form-two-columns"><?=csrf_field()?><input type="hidden" name="action" value="save"><input type="hidden" name="election_id" value="<?=$electionId?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>">
<label>ФИО<input name="full_name" value="<?=e($edit['full_name']??'')?>" required <?=$editable?'':'disabled'?>></label><label>Класс<input name="class_name" value="<?=e($edit['class_name']??'')?>" required <?=$editable?'':'disabled'?>></label><label>Номер в бюллетене<input type="number" min="0" name="ballot_number" value="<?=e($edit['ballot_number']??0)?>" <?=$editable?'':'disabled'?>></label><label>Цвет<input type="color" name="color" value="<?=e($edit['color']??'#665df5')?>" <?=$editable?'':'disabled'?>></label><label class="full-column">Слоган<input name="slogan" value="<?=e($edit['slogan']??'')?>" <?=$editable?'':'disabled'?>></label><label class="full-column">Программа — каждый пункт с новой строки<textarea name="program_text" rows="5" <?=$editable?'':'disabled'?>><?=e($edit['program_text']??'')?></textarea></label><label class="full-column">Биография<textarea name="bio" rows="4" <?=$editable?'':'disabled'?>><?=e($edit['bio']??'')?></textarea></label><label class="full-column">Достижения — каждое с новой строки<textarea name="achievements" rows="4" <?=$editable?'':'disabled'?>><?=e($edit['achievements']??'')?></textarea></label><label>Видео URL<input type="url" name="video_url" value="<?=e($edit['video_url']??'')?>" <?=$editable?'':'disabled'?>></label><label>Сайт проекта<input type="url" name="website_url" value="<?=e($edit['website_url']??'')?>" <?=$editable?'':'disabled'?>></label><label class="full-column">Материалы: Название | URL, по одному на строку<textarea name="resources_text" rows="4" <?=$editable?'':'disabled'?>><?=e($edit['resources_text']??'')?></textarea></label><label>Фотография JPG/PNG/WEBP<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" <?=$editable?'':'disabled'?>></label><div class="form-end"><?php if($editable):?><button class="button primary">Сохранить</button><?php endif;?></div></form></section>
<div class="candidate-admin-grid"><?php foreach($candidates as $candidate):?><article class="candidate-card admin-candidate-card <?=$candidate['is_active']?'':'is-disabled'?>"><?php if($candidate['photo_path']):?><img class="candidate-photo" src="../<?=e($candidate['photo_path'])?>" alt=""><?php else:?><div class="candidate-avatar" style="--candidate-color:<?=e($candidate['color'])?>"><?=e(candidate_initials($candidate['full_name']))?></div><?php endif;?><div class="candidate-admin-meta"><span class="mini-status <?=$candidate['is_active']?'mini-active':'mini-disabled'?>"><?=$candidate['is_active']?'Активен':'Скрыт'?></span><span><?=(int)$candidate['vote_count']?> голосов</span></div><span class="candidate-class">№<?=(int)$candidate['ballot_number']?> · <?=e($candidate['class_name'])?></span><h3><?=e($candidate['full_name'])?></h3><p class="candidate-slogan"><?=e($candidate['slogan'])?></p><div class="card-actions"><a class="button secondary small" href="?election_id=<?=$electionId?>&edit=<?=(int)$candidate['id']?>">Изменить</a><a class="button secondary small" target="_blank" href="../candidate.php?id=<?=(int)$candidate['id']?>">Страница</a><?php if($editable):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="election_id" value="<?=$electionId?>"><input type="hidden" name="id" value="<?=(int)$candidate['id']?>"><button class="button secondary small"><?=$candidate['is_active']?'Скрыть':'Показать'?></button></form><?php if((int)$candidate['vote_count']===0):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="election_id" value="<?=$electionId?>"><input type="hidden" name="id" value="<?=(int)$candidate['id']?>"><button class="button danger-button small" data-confirm="Удалить кандидата?">Удалить</button></form><?php endif;?><?php endif;?></div></article><?php endforeach;?><?php if(!$candidates):?><div class="empty-state">Кандидаты не добавлены.</div><?php endif;?></div>

<?php if($editable&&($admin['role']??'')==='superadmin'):?>
<section class="panel danger-panel candidate-danger-panel"><div class="panel-heading"><div><span class="kicker">Массовое удаление</span><h2>Удалить всех кандидатов одной кнопкой</h2><p>Действие доступно только пока в выбранных выборах нет голосов. Перед удалением автоматически создаётся резервная копия базы.</p></div></div><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete_all"><input type="hidden" name="election_id" value="<?=$electionId?>"><button class="button danger-button" data-confirm="Удалить всех кандидатов выбранных выборов? Перед операцией будет создана резервная копия.">Удалить всех кандидатов</button></form></section>
<?php endif;?>
</div></section>
<?php require dirname(__DIR__).'/partials/footer.php';?>
