<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/functions.php';
$admin=require_admin('students');

if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='generate_batch'){
            $ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['student_ids']??[])))));if(!$ids)throw new RuntimeException('Выберите хотя бы одного ученика.');if(count($ids)>500)throw new RuntimeException('За один раз можно подготовить не более 500 карточек.');$placeholders=implode(',',array_fill(0,count($ids),'?'));$st=db()->prepare("SELECT id,student_code,full_name,class_name FROM students WHERE id IN ($placeholders) AND is_active=1 ORDER BY class_name,full_name");$st->execute($ids);$students=$st->fetchAll();$update=db()->prepare('UPDATE students SET password_hash=?,session_token=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?');$batch=[];$pdo=db();$pdo->beginTransaction();foreach($students as $s){$password=random_password(8);$update->execute([student_password_hash($password),(int)$s['id']]);$s['password']=$password;$s['qr_url']=app_base_url().'/login.php?'.http_build_query(['student'=>(int)$s['id'],'code'=>$s['student_code'],'sig'=>student_qr_signature((int)$s['id'],$s['student_code'])]);$batch[]=$s;}$pdo->commit();$_SESSION['credential_batch']=['created_at'=>time(),'items'=>$batch];audit_log('credential_cards_generated','students',null,['count'=>count($batch)]);redirect('cards.php?print=1');
        }elseif($action==='clear'){unset($_SESSION['credential_batch']);flash('success','Временные пароли удалены из сессии.');redirect('cards.php');}
    }catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());redirect('cards.php');}
}
$class=trim((string)($_GET['class']??''));$params=[];$sql='SELECT id,student_code,full_name,class_name FROM students WHERE is_active=1';if($class!==''){$sql.=' AND class_name=?';$params[]=$class;}$sql.=' ORDER BY class_name,full_name';$st=db()->prepare($sql);$st->execute($params);$students=$st->fetchAll();$classes=db()->query('SELECT DISTINCT class_name FROM students WHERE is_active=1 ORDER BY class_name')->fetchAll(PDO::FETCH_COLUMN);$batch=$_SESSION['credential_batch']??null;if($batch&&time()-(int)$batch['created_at']>1800){unset($_SESSION['credential_batch']);$batch=null;}
$pageTitle='Карточки доступа';$isAdminArea=true;require dirname(__DIR__).'/partials/header.php';
?>
<section class="section"><div class="container">
<div class="dashboard-heading no-print"><div><span class="kicker">QR и учётные данные</span><h1>Карточки доступа</h1><p class="lead">QR-код открывает форму входа с заполненным кодом. Пароль остаётся отдельным секретом.</p></div><?php if($batch):?><div class="actions"><button class="button primary" onclick="window.print()">Печатать карточки</button><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="clear"><button class="button secondary">Закрыть пакет</button></form></div><?php endif;?></div>
<?php if($batch):?><div class="flash flash-warning no-print">Пароли показываются только в этом временном пакете, максимум 30 минут. После печати закройте пакет.</div><div class="credential-cards"><?php foreach($batch['items'] as $item):?><article class="credential-card"><header><span class="brand-mark">ШВ</span><div><strong><?=e(setting('school_name',APP_NAME))?></strong><small>Персональная карточка ученика</small></div></header><div class="credential-qr" data-qr="<?=e($item['qr_url'])?>"></div><h2><?=e($item['full_name'])?></h2><p><?=e($item['class_name'])?></p><dl><div><dt>Код</dt><dd><?=e($item['student_code'])?></dd></div><div><dt>Пароль</dt><dd><?=e($item['password'])?></dd></div></dl><small class="card-note">Не передавайте карточку другим ученикам. После голосования вход закрывается автоматически.</small></article><?php endforeach;?></div><?php else:?><section class="panel no-print"><div class="panel-heading"><div><span class="kicker">Создание пакета</span><h2>Выберите учеников</h2></div><form method="get"><select name="class" onchange="this.form.submit()"><option value="">Все классы</option><?php foreach($classes as $c):?><option <?=$class===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></form></div><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="generate_batch"><div class="selection-toolbar"><label class="check-row"><input type="checkbox" data-select-all><span>Выбрать всех показанных</span></label><button class="button primary" data-confirm="Для выбранных учеников будут созданы новые пароли. Старые пароли перестанут работать. Продолжить?">Создать новые пароли и карточки</button></div><div class="student-selection"><?php foreach($students as $s):?><label><input type="checkbox" name="student_ids[]" value="<?=(int)$s['id']?>"><span><strong><?=e($s['full_name'])?></strong><small><?=e($s['class_name'])?> · <?=e($s['student_code'])?></small></span></label><?php endforeach;?></div></form></section><?php endif;?>
</div></section>
<?php require dirname(__DIR__).'/partials/footer.php';?>
