<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/functions.php';
require_once dirname(__DIR__).'/xlsx_export.php';
require_once dirname(__DIR__).'/student_import.php';
$admin=require_admin('reports');$type=(string)($_GET['type']??'');$electionId=(int)($_GET['id']??active_election_id());$election=election_by_id($electionId);

function send_csv(string $filename,array $headers,array $rows):never{header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');fputcsv($out,$headers,';');foreach($rows as $row)fputcsv($out,$row,';');fclose($out);exit;}
function send_xlsx(string $filename,array $headers,array $rows,string $sheet):never{$path=create_xlsx_file($headers,$rows,$sheet);header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Content-Length: '.filesize($path));readfile($path);@unlink($path);exit;}

if($type==='import_errors'){$token=(string)($_SESSION['student_import_job_token']??'');if($token==='')exit('Предпросмотр импорта не найден.');$rows=[];foreach(student_import_error_records($token) as $r){$rows[]=[(int)$r['source_row'],$r['student_code'],$r['full_name'],$r['class_name'],implode(', ',$r['errors'])];}send_csv('student-import-errors-'.date('Ymd-His').'.csv',['Строка','Код','ФИО','Класс','Ошибки'],$rows);}
if(in_array($type,['students_csv','students_xlsx'],true)){$data=db()->query('SELECT student_code,full_name,class_name,is_active,created_at FROM students ORDER BY class_name,full_name')->fetchAll();$rows=array_map(static fn($r)=>[$r['student_code'],$r['full_name'],$r['class_name'],$r['is_active']?'Активен':'Отключён',$r['created_at']],$data);audit_log('students_exported','students',null,['format'=>$type]);$headers=['Код','ФИО','Класс','Статус','Создан'];$type==='students_csv'?send_csv('students-'.date('Ymd').'.csv',$headers,$rows):send_xlsx('students-'.date('Ymd').'.xlsx',$headers,$rows,'Ученики');}
if(!$election)exit('Выборы не найдены.');
if(in_array($type,['results_csv','results_xlsx'],true)){$data=result_rows($electionId);$total=array_sum(array_map(static fn($r)=>(int)$r['vote_count'],$data));$rows=[];foreach($data as $i=>$r){$rows[]=[$i+1,$r['ballot_number'],$r['full_name'],$r['class_name'],(int)$r['vote_count'],$total?round((int)$r['vote_count']/$total*100,2):0];}$headers=['Место','№','Кандидат','Класс','Голоса','Процент'];audit_log('results_exported','election',$electionId,['format'=>$type]);$type==='results_csv'?send_csv('results-'.$electionId.'.csv',$headers,$rows):send_xlsx('results-'.$electionId.'.xlsx',$headers,$rows,'Результаты');}
if($type==='turnout_xlsx'){$data=turnout_by_class($electionId);$rows=array_map(static fn($r)=>[$r['class_name'],(int)$r['eligible'],(int)$r['participated'],(int)$r['eligible']-(int)$r['participated'],(float)$r['turnout']],$data);audit_log('turnout_exported','election',$electionId);send_xlsx('turnout-'.$electionId.'.xlsx',['Класс','Учеников','Проголосовали','Не проголосовали','Явка %'],$rows,'Явка');}
if($type==='participation_csv'){$st=db()->prepare('SELECT election_eligibility.student_code,election_eligibility.full_name,election_eligibility.class_name,participation.voted_at FROM election_eligibility LEFT JOIN participation ON participation.student_code=election_eligibility.student_code AND participation.election_id=election_eligibility.election_id WHERE election_eligibility.election_id=? ORDER BY election_eligibility.class_name,election_eligibility.full_name');$st->execute([$electionId]);$data=$st->fetchAll();$rows=array_map(static fn($r)=>[$r['student_code'],$r['full_name'],$r['class_name'],$r['voted_at']?'Участвовал':'Не участвовал',$r['voted_at']??''],$data);audit_log('participation_exported','election',$electionId);send_csv('participation-'.$electionId.'.csv',['Код','ФИО','Класс','Участие','Время'],$rows);}
if($type==='protocol'){$rows=result_rows($electionId);$metrics=election_metrics($electionId);$classes=turnout_by_class($electionId);audit_log('protocol_opened','election',$electionId);?><!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Протокол — <?=e($election['title'])?></title><style>body{font:14px Arial,sans-serif;color:#111;margin:30px}h1{font-size:25px}h2{margin-top:30px}table{width:100%;border-collapse:collapse;margin:15px 0}th,td{border:1px solid #777;padding:8px;text-align:left}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:60px}.print{position:fixed;right:20px;top:20px;padding:10px 16px}@media print{.print{display:none}body{margin:0}}</style></head><body><button class="print" onclick="window.print()">Печать / сохранить PDF</button><h1>Итоговый протокол школьных выборов</h1><div class="meta"><div><strong>Кампания:</strong> <?=e($election['title'])?></div><div><strong>Статус:</strong> <?=e(election_status_label($election['status']))?></div><div><strong>Начало:</strong> <?=e(format_datetime($election['start_at']))?></div><div><strong>Окончание:</strong> <?=e(format_datetime($election['end_at']))?></div><div><strong>Участников:</strong> <?=$metrics['participants']?> из <?=$metrics['eligible']?></div><div><strong>Явка:</strong> <?=$metrics['turnout']?>%</div></div><h2>Результаты кандидатов</h2><table><thead><tr><th>Место</th><th>Кандидат</th><th>Класс</th><th>Голоса</th><th>%</th></tr></thead><tbody><?php $total=max(1,$metrics['votes']);foreach($rows as $i=>$r):?><tr><td><?=$i+1?></td><td><?=e($r['full_name'])?></td><td><?=e($r['class_name'])?></td><td><?=(int)$r['vote_count']?></td><td><?=round((int)$r['vote_count']/$total*100,2)?></td></tr><?php endforeach;?></tbody></table><h2>Явка по классам</h2><table><thead><tr><th>Класс</th><th>Всего</th><th>Участвовали</th><th>Явка</th></tr></thead><tbody><?php foreach($classes as $c):?><tr><td><?=e($c['class_name'])?></td><td><?=(int)$c['eligible']?></td><td><?=(int)$c['participated']?></td><td><?=e($c['turnout'])?>%</td></tr><?php endforeach;?></tbody></table><p>Система хранит факт участия отдельно от анонимных голосов. Протокол сформирован <?=e(date('d.m.Y H:i:s'))?>.</p><div class="signatures"><div>Председатель комиссии: __________________</div><div>Секретарь комиссии: __________________</div></div></body></html><?php exit;}
http_response_code(400);echo 'Неизвестный формат экспорта.';
